# Renders a code-derived architecture data-flow diagram (Mermaid) from graphify-out/graph.json.

import json
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GRAPH = ROOT / "graphify-out" / "graph.json"
OUT = ROOT / "docs" / "architecture.generated.mmd"

# Process boundaries the AST cannot see; each carries the file:line that proves it exists.
CROSS_PROCESS = [
    ("harness/src/capabilities", "src/forecasting_agent/data_server", "MCP stdio", "harness/harness_config.yaml:13"),
    ("harness/src/sandbox", "sandbox/entrypoints", "Docker exec", "harness/src/sandbox/manager.ts:110"),
    (
        "sandbox/entrypoints",
        "src/forecasting_agent/evaluation",
        "in-container import",
        "harness/src/sandbox/manager.ts:123",
    ),
    ("harness/src/search", "external", "HTTPS search MCP", "harness/harness_config.yaml:7"),
    ("harness/src/llm", "external", "DeepSeek API", "harness/harness_config.yaml:2"),
    ("src/forecasting_agent/data_server", "external", "AngelOne / NSE HTTP", "harness/harness_config.yaml:16"),
]

LAYERS = {
    "Entry Points": ["harness/scripts", "scripts"],
    "Agent Runtime (TS)": ["harness/src/pipeline", "harness/src/debate", "harness/src/agents", "harness/src/prompts"],
    "Platform (TS)": [
        "harness/src/capabilities",
        "harness/src/search",
        "harness/src/sandbox",
        "harness/src/llm",
        "harness/src/storage",
        "harness/src/tracing",
        "harness/src/middleware",
        "harness/src/backend",
    ],
    "Market Data (PY)": [
        "src/forecasting_agent/data_server",
        "src/forecasting_agent/data_server/plugins",
        "src/forecasting_agent/archive",
        "src/forecasting_agent/archive/downloaders",
    ],
    "Evaluation (PY)": ["src/forecasting_agent/evaluation", "sandbox/entrypoints"],
}
MIN_EDGE_WEIGHT = 3  # below this, an edge is a single-symbol reference, not architecture.
SKIP = re.compile(r"(^|/)tests?/|node_modules|__pycache__|\.json$|\.yaml$|\.yml$|\.md$|\.sql$")


def group_of(path: str) -> str | None:
    """Takes a source file path; returns the diagram group it belongs to, or None to drop it."""
    if not path or SKIP.search(path):
        return None
    for layer_dirs in LAYERS.values():
        for d in sorted(layer_dirs, key=len, reverse=True):
            if path.startswith(d + "/"):
                return d
    return None


def node_id(group: str) -> str:
    """Takes a group path; returns a Mermaid-safe node identifier."""
    return re.sub(r"[^A-Za-z0-9]", "_", group)


def leaf(group: str, used: set[str]) -> str:
    """Takes a group and every group in the diagram; returns its shortest label that stays unique."""
    tail = group.split("/")[-1]
    clashes = sum(1 for other in used if other.split("/")[-1] == tail)
    return tail if clashes < 2 else "/".join(group.split("/")[-2:])


def build() -> str:
    """Takes no arguments (reads graph.json); returns the Mermaid diagram source."""
    g = json.loads(GRAPH.read_text())
    files = {n["id"]: n.get("source_file") for n in g["nodes"]}
    edges: Counter[tuple[str, str]] = Counter()
    for link in g["links"]:
        a, b = group_of(files.get(link["source"]) or ""), group_of(files.get(link["target"]) or "")
        if a and b and a != b:
            edges[(a, b)] += 1

    used = {n for pair in edges for n in pair} | {n for a, b, _, _ in CROSS_PROCESS for n in (a, b)}
    lines = [
        "%% Generated by scripts/graph_to_architecture.py from graphify-out/graph.json — do not hand-edit.",
        f"%% commit {g.get('built_at_commit', '?')[:8]} | {len(g['nodes'])} symbols, {len(g['links'])} edges",
        "flowchart TB",
    ]
    for layer, dirs in LAYERS.items():
        members = [d for d in dirs if d in used]
        if not members:
            continue
        lines.append(f'  subgraph {node_id(layer)}["{layer}"]')
        for d in members:
            lines.append(f'    {node_id(d)}["{leaf(d, used)}"]')
        lines.append("  end")
    if "external" in used:
        lines.append('  external{{"External APIs"}}')

    for (a, b), w in sorted(edges.items(), key=lambda kv: -kv[1]):
        if w < MIN_EDGE_WEIGHT:
            continue
        lines.append(f"  {node_id(a)} -->|{w}| {node_id(b)}")
    for a, b, label, cite in CROSS_PROCESS:
        lines.append(f"  {node_id(a)} -.->|{label}| {node_id(b)}")
        lines.append(f"  %% ^ {cite}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    OUT.write_text(build())
    print(f"wrote {OUT.relative_to(ROOT)}")
