"""DSPy Prompt Compiler and Template Exporter (ADR-028)."""

from pathlib import Path
from typing import Any

import dspy
from dspy.teleprompt import BootstrapFewShot

from forecasting_agent.prompt_compiler.dataset import get_fii_examples, get_price_anchor_examples
from forecasting_agent.prompt_compiler.metrics import m8_prompt_metric
from forecasting_agent.prompt_compiler.signatures import (
    FIISignature,
    PriceAnchorSignature,
)


class PromptCompiler:
    """Compiles and optimizes subagent prompts offline using DSPy and exports to Jinja2/Nunjucks."""

    def __init__(
        self,
        model_name: str = "deepseek/deepseek-chat",
        api_key: str | None = None,
        api_base: str | None = None,
    ) -> None:
        self.model_name = model_name
        self.api_key = api_key
        self.api_base = api_base
        self._configured_lm: dspy.LM | None = None

    def configure_lm(self) -> dspy.LM:
        """Initializes and registers the DSPy Language Model client."""
        if self._configured_lm is None:
            kwargs: dict[str, Any] = {"model": self.model_name}
            if self.api_key:
                kwargs["api_key"] = self.api_key
            if self.api_base:
                kwargs["api_base"] = self.api_base
            self._configured_lm = dspy.LM(**kwargs)
            dspy.configure(lm=self._configured_lm)
        return self._configured_lm

    def build_program(self, signature_cls: type[dspy.Signature]) -> dspy.Module:
        """Builds a DSPy Predict or ChainOfThought module for the given signature."""
        return dspy.ChainOfThought(signature_cls)

    def compile_price_agent(
        self,
        trainset: list[dspy.Example] | None = None,
        max_bootstrapped_demos: int = 2,
        max_labeled_demos: int = 2,
    ) -> dspy.Module:
        """Compiles and optimizes the Price Anchor agent prompt using BootstrapFewShot / MIPRO."""
        trainset = trainset or get_price_anchor_examples()
        student = self.build_program(PriceAnchorSignature)

        teleprompter = BootstrapFewShot(
            metric=m8_prompt_metric,
            max_bootstrapped_demos=max_bootstrapped_demos,
            max_labeled_demos=max_labeled_demos,
        )

        compiled_program = teleprompter.compile(student, trainset=trainset)
        return compiled_program

    def compile_fii_agent(
        self,
        trainset: list[dspy.Example] | None = None,
        max_bootstrapped_demos: int = 2,
        max_labeled_demos: int = 2,
    ) -> dspy.Module:
        """Compiles and optimizes the FII agent prompt."""
        trainset = trainset or get_fii_examples()
        student = self.build_program(FIISignature)

        teleprompter = BootstrapFewShot(
            metric=m8_prompt_metric,
            max_bootstrapped_demos=max_bootstrapped_demos,
            max_labeled_demos=max_labeled_demos,
        )

        compiled_program = teleprompter.compile(student, trainset=trainset)
        return compiled_program

    def export_compiled_exemplars(self, compiled_program: dspy.Module, output_file: Path) -> None:
        """Exports optimized few-shot exemplars and instructions to a Jinja2 partial template."""
        demos: list[Any] = []
        for predictor in compiled_program.predictors():
            demos.extend(getattr(predictor, "demos", []))
        if not demos and hasattr(compiled_program, "demos"):
            demos = getattr(compiled_program, "demos", [])

        lines = ["{# Autogenerated by DSPy PromptCompiler (ADR-028) #}"]
        lines.append("{% set compiled_demos = [")
        for demo in demos:
            demo_dict = demo.toDict() if hasattr(demo, "toDict") else dict(demo)
            lines.append(f"  {demo_dict!r},")
        lines.append("] %}")
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_text("\n".join(lines), encoding="utf-8")
